services:
  web:
    build: .
    container_name: pa_python_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    stdin_open: true
    tty: true
    networks:
      - pa_network

networks:
  pa_network:
    driver: bridge