[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"


[project]
name = "PA-in-python"
version = "0.1.0"
dependencies = ["Django>=6.0.2"]
requires-python = ">= 3.12"

authors = [
  {name = "Juan Chamorro", email = "clon5454@outlook.com"},
  {name = "Luis Tejada"},
  {name = "Naikel Jaraba"},
]

readme = "readme.md"

[project.urls]
Repository = "https://github.com/clon54programer/PA-de-desarrollo-de-software.git"

[tool.setuptools]
packages = ["src"] # 