# Generated by Django 6.0.3 on 2026-04-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scanresult",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="service",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="detectedvulnerability",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="cveaffectedproduct",
            name="cve",
        ),
        migrations.RemoveField(
            model_name="detectedvulnerability",
            name="cve",
        ),
        migrations.RemoveField(
            model_name="exploit",
            name="cve",
        ),
        migrations.RemoveField(
            model_name="detectedvulnerability",
            name="service",
        ),
        migrations.RemoveField(
            model_name="remediationticket",
            name="vulnerability",
        ),
        migrations.RemoveField(
            model_name="scanresult",
            name="scan",
        ),
        migrations.AlterUniqueTogether(
            name="service",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="scanresult",
            name="service",
        ),
        migrations.RenameField(
            model_name="scanresult",
            old_name="created_at",
            new_name="fecha",
        ),
        migrations.RemoveField(
            model_name="scanresult",
            name="nmap_output",
        ),
        migrations.RemoveField(
            model_name="scanresult",
            name="raw_data",
        ),
        migrations.AddField(
            model_name="scanresult",
            name="data_json",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="dominio",
            field=models.CharField(default="127.0.0.2", max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Asset",
        ),
        migrations.DeleteModel(
            name="CVEAffectedProduct",
        ),
        migrations.DeleteModel(
            name="CVECatalog",
        ),
        migrations.DeleteModel(
            name="Exploit",
        ),
        migrations.DeleteModel(
            name="DetectedVulnerability",
        ),
        migrations.DeleteModel(
            name="RemediationTicket",
        ),
        migrations.DeleteModel(
            name="Scan",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
