# Generated by Django 6.0.3 on 2026-05-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceresult",
            name="scan_name",
            field=models.CharField(default="Sin nombre", max_length=120),
            preserve_default=False,
        ),
    ]
