# Generated by Django 6.0.3 on 2026-04-15 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_remove_scanresult_asset_remove_service_asset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("hostname", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "hostname_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("scan_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="scanresult",
            name="data_json",
        ),
        migrations.CreateModel(
            name="ServiceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protocol", models.CharField(max_length=10)),
                ("port", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("product", models.CharField(blank=True, max_length=255, null=True)),
                ("version", models.CharField(blank=True, max_length=100, null=True)),
                ("extrainfo", models.CharField(blank=True, max_length=255, null=True)),
                ("reason", models.CharField(blank=True, max_length=100, null=True)),
                ("conf", models.CharField(blank=True, max_length=50, null=True)),
                ("cpe", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "host_scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="polls.hostscan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scanresult",
            name="servicio",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escaneos",
                to="polls.serviceresult",
            ),
            preserve_default=False,
        ),
    ]
